#ifndef _SRC_CAPTURE_STATUS_CODE_H_
#define _SRC_CAPTURE_STATUS_CODE_H_

#include <string>

namespace media
{
enum StatusCode
{
	CAPTURE_OK = 0,
	CAPTURE_ERROR_BITBIT,
	CAPTURE_ALLOC_FAILED,
	CAPTURE_GETBITS_FAILED,
	CAPTURE_INVALID_PARAMETER,
    CAPTURE_NO_IMPLEMENT,
    CAPTURE_GET_DIBITS_FAILED,
};
}

#endif // _SRC_CAPTURE_STATUS_CODE_H_